FROM python:3.7


# CONFIGURACION
ARG TAG=latest

WORKDIR /usr/src/


# DEPENDENCIAS
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt 


# VARIABLES PREDEFINIDAS
ENV SQL_EXECUTOR_VERSION=${TAG}

ENV DRUID_INJECTOR_PYTHON_HOST=0.0.0.0
ENV DRUID_INJECTOR_PYTHON_PORT=5000
ENV DRUID_INJECTOR_PYTHON_GUNICORN_WORKERS=2
ENV DRUID_INJECTOR_PYTHON_GUNICORN_CONNECTIONS=500
ENV DRUID_INJECTOR_PYTHON_GUNICORN_TIMEOUT=360

ENV DRUID_INJECTOR_PYTHON_NOMBRE_APP=app
ENV DRUID_INJECTOR_PYTHON_NOMBRE_FUNCION_APP=app


# EJECUCION
EXPOSE ${PYTHON_PORT}

CMD gunicorn \
    -b ${DRUID_INJECTOR_PYTHON_HOST}:${DRUID_INJECTOR_PYTHON_PORT} \
    --reload \
    --timeout $DRUID_INJECTOR_PYTHON_GUNICORN_TIMEOUT \
    --workers=${DRUID_INJECTOR_PYTHON_GUNICORN_WORKERS} \
    --worker-connections=${DRUID_INJECTOR_PYTHON_GUNICORN_CONNECTIONS} \
    ${DRUID_INJECTOR_PYTHON_NOMBRE_APP}:${DRUID_INJECTOR_PYTHON_NOMBRE_FUNCION_APP}


# PROYETO
COPY ./apps ./apps
COPY ./app.py .
COPY ./files ./files
