from enum import Enum


class Vars(Enum):
    DEBUG_MODE = "DEBUG_MODE"
    API_HOST = "PYTHON_HOST"
    API_PORT = "PYTHON_PORT"
    API_BASE_PATH = "API_BASE_PATH"
    LOG_LEVELS = "LOG_LEVELS"
    DIRECTORIO_LOGS = "DIRECTORIO_LOGS"
    DRUID_HOST = "DRUID_HOST"
    DRUID_PORT = "DRUID_PORT"
    REDIS_HOST="REDIS_HOST"
    REDIS_PORT="REDIS_PORT"
    REDIS_PASSWD="REDIS_PASSWD"
